name: minigalaxy
base: core24
version: 1.4.1
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
summary: A simple GOG client for Linux
description: |
 Minigalaxy lets you download, install and play your GOG Linux games without getting in your way. 
grade: stable
confinement: strict
compression: lzo
icon: minigalaxy.png

apps:
  minigalaxy:
    command-chain:
      - snap/command-chain/gpu-2404-wrapper
      - snap/command-chain/desktop-launch
    command: snap/command-chain/request-joystick-plug
    desktop: usr/share/applications/io.github.sharkwouter.Minigalaxy.desktop
    common-id: io.github.sharkwouter.Minigalaxy
    environment:
      HOME: $SNAP_USER_COMMON
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      PATH: $SNAP/usr/games:$SNAP/opt/wine-stable/bin:$PATH
      LD_LIBRARY_PATH: $SNAP/opt/wine-stable/lib/wine/i386-unix:$SNAP/wine-kyu/usr/lib/i386-linux-gnu:$SNAP/wine-kyu/usr/lib/i386-linux-gnu/pulseaudio:$SNAP/opt/wine-stable/lib/wine/x86_64-unix:$SNAP/wine-kyu/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - wayland
      - x11
      - audio-playback
      - network
      - network-bind
      - network-status
      - screen-inhibit-control
      - home
      - removable-media
      - mount-observe
      - system-observe
      - joystick
      - bluez

environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
  GTK_USE_PORTAL: '1'

plugs:
  shared-memory:
    private: true
  desktop:
    mount-host-font-cache: false
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  gnome-46-2404:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-46-2404
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
  wine-kyu:
    content: wine-kyu
    interface: content
    target: $SNAP/wine-kyu
    default-provider: wine-kyu

layout:
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0:
    symlink: $SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.1:
    symlink: $SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1
  /usr/share/xml/iso-codes:
    bind: $SNAP/gnome-platform/usr/share/xml/iso-codes
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/gpu-2404/X11/XErrorDB
  /usr/lib/x86_64-linux-gnu/mangohud:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/mangohud
  /opt/wine-stable:
    symlink: $SNAP/wine-kyu/opt/wine-stable
  /usr/bin/wine:
    symlink: $SNAP/wine-kyu/opt/wine-stable/bin/wine

hooks:
  configure:
    command-chain:
      - snap/command-chain/hooks-configure-fonts

#package-repositories:
#  - type: apt
#    url: https://dl.winehq.org/wine-builds/ubuntu
#    suites: [resolute]
#    components: [main]
#    architectures: [amd64]
#    key-id: D43F640145369C51D786DDEA76F1A20FF987672F

parts:
  minigalaxy-app:
    plugin: dump
    source: https://github.com/sharkwouter/minigalaxy/releases/download/$SNAPCRAFT_PROJECT_VERSION/minigalaxy_$SNAPCRAFT_PROJECT_VERSION_all.deb
    override-build: |
      craftctl default
      sed -i 's|Name=Minigalaxy|Name=Minigalaxy [Kyu]|' $CRAFT_PART_INSTALL/usr/share/applications/io.github.sharkwouter.Minigalaxy.desktop

  base-dependencies:
    after: [minigalaxy-app]
    plugin: nil
    stage-packages: [python3-requests, unzip, unrar-free]

  gamemode:
    plugin: nil
    stage-packages: [gamemode, gamemode-daemon, libgamemode0, libgamemodeauto0]
    prime:
      - etc/security/limits.d/10-gamemode.conf
      - usr/bin/gamemoded
      - usr/games/gamemodelist
      - usr/games/gamemoderun
      - usr/games/gamemode-simulate-game
      - usr/lib/x86_64-linux-gnu/libgamemode.so*
      - usr/lib/x86_64-linux-gnu/libgamemodeauto.so*
      - usr/lib/x86_64-linux-gnu/libinih.so*
      - usr/lib/systemd/user/gamemoded.service
      - usr/lib/sysusers.d/gamemode.conf
      - usr/libexec/cpucorectl
      - usr/libexec/cpugovctl
      - usr/libexec/gpuclockctl
      - usr/libexec/procsysctl
      - usr/share/dbus-1/services/com.feralinteractive.GameMode.service
      - usr/share/gamemode/gamemode.ini
      - usr/share/lintian/overrides/libgamemode0
      - usr/share/metainfo/io.github.feralinteractive.gamemode.metainfo.xml
      - usr/share/polkit-1/actions/com.feralinteractive.GameMode.policy
      - usr/share/polkit-1/rules.d/gamemode.rules

  mangohud:
    plugin: nil
    stage-packages: [mangohud, libspdlog1.12, libfmt9]
    prime:
      - usr/bin/mangohud
      - usr/lib/x86_64-linux-gnu/mangohud
      - usr/lib/x86_64-linux-gnu/libspdlog.so*
      - usr/lib/x86_64-linux-gnu/libfmt.so*
      - usr/share/metainfo/io.github.flightlessmango.mangohud.metainfo.xml
      - usr/share/vulkan/implicit_layer.d/MangoHud.x86_64.json

  sdl2:
    plugin: nil
    stage-packages: [libsdl2-2.0-0, libdecor-0-0, libsamplerate0]

  zenity:
    plugin: nil
    stage-packages: [zenity]
    prime: [usr/bin/zenity]

#  wine:
#    plugin: nil
#    stage-packages: [winehq-stable, winetricks]

  cleanup:
    after: [minigalaxy-app, base-dependencies, gamemode, mangohud, zenity] #, wine]
    plugin: nil
    build-snaps:
      - mesa-2404
      - gnome-46-2404
    override-prime: |
      set -eux
      cd /snap/mesa-2404/current/usr/lib
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/lib/{} \;
      cd /snap/mesa-2404/current/usr/share
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/share/{} \;

      cd /snap/gnome-46-2404/current/usr/lib
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/lib/{} \;
      cd /snap/gnome-46-2404/current/usr/share
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/share/{} \;

  command-chain:
    after: [cleanup]
    plugin: dump
    source: .
    organize:
      command-chain: snap/command-chain
    prime:
      - snap
